version: '3.3'                                   
services:                                        
 mysql:                                           
  image: 'mariadb:10.6.8'                  
  container_name: mysql
#  ports:
#    - "8095:3306"                         
  env_file:
    - ./env/mysql.env
  volumes:
    - ./data/mysql:/var/lib/mysql
 phpmyadmin_test:
  image: 'phpmyadmin/phpmyadmin'
  container_name: phpmyadmin_test
  links:
    - "mysql:mysql"
  env_file: 
    - ./env/phpmyadmin.env
  ports:
    - 8082:80
 php:
   build:
     context: ./php
     dockerfile: Dockerfile
   ports:
     - 7000:7000
   volumes:
    - ./php/Hotel-Management:/Hotel-Management
volumes:
    mysql:
    Hotel-Management:


